name: CI for next-js

on:
  push:
    branches: [production] ## can multiple branch if in array

jobs:
  deploy-production:
    name: Deploying to production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production' ## check if current ref is production
    steps:
      - name: Checkout latest code from GH
        uses: actions/checkout@v2 ## use existing GH actions for checkout
      - name: Rsync to production server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.SERVER_DIR_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
      - name: Run npm install, build and reload pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            whoami
            cd ~/nodejs/nextjs
            npm install
            npm run build --if-present
            pm2 reload next-js