name: Say Hello Guys When Issues Opened

on:
  issues:
    types: [opened]
  
jobs:
  run-commands:
    name: issue has been opened
    runs-on: ubuntu-latest
    steps:
      - name: run bash commands
        run: echo "hello guys"
      - name: comment to new issues
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
      - name: View context attributes
        uses: actions/github-script@v5
        with:
          script: console.log(context)